services:
  - type: web
    name: vinyl-barcode-scanner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd barcode-scanner && gunicorn server:app
    envVars:
      - key: DISCOGS_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    plan: free 
